# Docker profile configuration
# This profile is used when running in Docker containers

spring:
  datasource:
    url: jdbc:postgresql://postgres.tailce422e.ts.net:5432/MoneyPlant
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-init-sql: SET default_transaction_isolation = 'read committed'
      # Additional connection properties for external database
      connection-test-query: SELECT 1
      # SSL configuration for external database
      data-source-properties:
        ssl: false
        sslmode: disable
      # Connection validation settings
      validation-timeout: 5000
      leak-detection-threshold: 60000


  jpa:
    hibernate:
      ddl-auto: update  # Use 'update' for external database to ensure schema exists
    show-sql: false
    # Transaction management configuration
    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        connection:
          auto_commit: false
          provider_disables_autocommit: true
        jdbc:
          batch_size: 20
          time_zone: UTC
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        # Additional transaction management properties
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
        # Explicitly set the dialect to avoid metadata issues
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432
    consumer:
      group-id: moneyplant-engines
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval-ms: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    admin:
      auto-create: false
      fail-on-error: false

# Kafka topic configuration
kafka:
  topics:
    nse-indices-ticks: nse-indices-ticks
    market-data: market-data
    trading-signals: trading-signals
    backtest-results: backtest-results
  group-id: moneyplant-engines

# NSE WebSocket configuration for Docker
nse:
  websocket:
    url: wss://www.nseindia.com/streams/indices/high/drdMkt
    reconnect:
      interval: 30
    enabled: false  # Disable NSE WebSocket connection in Docker
    fallback:
      enabled: false  # Disable fallback mock data in Docker

# Logging configuration for Docker
logging:
  level:
    com.moneyplant.engines: INFO
    org.springframework.kafka: INFO
    org.apache.kafka: INFO
    org.springframework.web.socket: INFO
    org.springframework.boot.autoconfigure.kafka: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints for Docker
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always
  metrics:
    export:
      prometheus:
        enabled: true

# Redis configuration for Docker
redis:
  host: redis
  port: 6379
  timeout: 2000ms
  lettuce:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
