name: Criteria Builder CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/projects/criteria-builder/**'
      - '.github/workflows/criteria-builder-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/projects/criteria-builder/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Run lint
      run: |
        cd frontend
        npm run lint:criteria-builder
    
    - name: Run unit tests
      run: |
        cd frontend
        npm run test:criteria-builder -- --watch=false --browsers=ChromeHeadless --code-coverage
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        file: frontend/projects/criteria-builder/coverage/lcov.info
        flags: criteria-builder
        name: criteria-builder-coverage
        fail_ci_if_error: false
  
  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Build library
      run: |
        cd frontend
        npm run build:criteria-builder
    
    - name: Run build tests
      run: |
        cd frontend/projects/criteria-builder
        node scripts/test.js --build-test
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: criteria-builder-dist
        path: frontend/dist/criteria-builder/
        retention-days: 30
  
  publish:
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Build library
      run: |
        cd frontend
        npm run build:criteria-builder
    
    - name: Publish to npm
      run: |
        cd frontend/dist/criteria-builder
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      if: env.NODE_AUTH_TOKEN != ''
  
  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Run security audit
      run: |
        cd frontend
        npm audit --audit-level moderate
    
    - name: Run dependency check
      run: |
        cd frontend/projects/criteria-builder
        npx license-checker --onlyAllow 'MIT;Apache-2.0;BSD-2-Clause;BSD-3-Clause;ISC' --excludePrivatePackages