package com.moneyplant.trading.common.enums;

public enum PatternType {
    DOJI,
    HAMMER,
    SHOOTING_STAR,
    ENGULFING_BULLISH,
    ENGULFING_BEARISH,
    MORNING_STAR,
    EVENING_STAR,
    THREE_WHITE_SOLDIERS,
    THREE_BLACK_CROWS,
    HANGING_MAN,
    INVERTED_HAMMER,
    SPINNING_TOP,
    MARUBOZU,
    PIERCING_LINE,
    DARK_CLOUD_COVER
}
