server:
  port: 8080

spring:
  application:
    name: moneyplant-trading-backend
  


  datasource:
    url: jdbc:postgresql://postgres.tailce422e.ts.net:5432/MoneyPlant
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Logging Configuration
logging:
  level:
    com.moneyplant.trading: INFO

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Screener Criteria Configuration
screener:
  criteria:
    validation:
      max-group-depth: 10
      max-conditions: 100
      max-function-params: 10
      enable-performance-warnings: true
      complexity-warning-threshold: 50
      strict-mode: false

 